name: 发布应用

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  actions: write

jobs:
  build_windows:
    name: 构建EXE
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 读入环境信息
        run: |
          echo "version=${{ github.ref }}"
      - name: 编译环境设置
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"
          architecture: "x64"
          cache: 'pip'
      - name: 下载依赖文件
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 编译exe
        run: |
          pyinstaller main-win.spec
      - name: 查看dist目录
        run: |
          ls ./dist
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: ./dist/*.exe

  release_version:
    needs: build_windows
    name: 发布版本
    runs-on: ubuntu-latest
    steps:
      - name: 下载
        id: download
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: .
      - name: 读入环境信息
        run: |
          echo "version=${{ github.ref }}"
          echo "download path: ${{ steps.download.outputs.download-path }}"
          ls -R
      - name: 编译环境设置
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"
          architecture: "x64"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - name: 发布文件
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: false
          tag: ${{ github.ref }}
          body: "发布内容"
          artifacts: "./*.exe"
